### ISSUE TITLE
다운로드 된 항목이 없습니다.

### ISSUE THREAD

**Issue by ghost** [Seo-Rii/Webtoon_Downloader_UI#4]
다운로드했는데 폴더에 아무것도 없습니다.
https://imgur.com/a/nt6Cciv

**Comment by ghost** [comment]
이것은 카카오 페이지에서만 일어나는 일입니다.

**Comment by seo-rii** [comment]
https://github.com/Seo-Rii/Webtoon_Downloader/issues/2

이 이슈에서 말한것처럼, 현재 카카오페이지의 API가 변경되어 다운로드가 되지 않습니다. 추후 수정할 예정이기는 한데 언제 가능할지는 모르겠네요;;;

**Comment by ghost** [comment]
> [Seo-Rii/Webtoon_Downloader#2](https://github.com/Seo-Rii/Webtoon_Downloader/issues/2)
> 
> 이 이슈에서 말한것처럼, 현재 카카오페이지의 API가 변경되어 다운로드가 되지 않습니다. 추후 수정할 예정이기는 한데 언제 가능할지는 모르겠네요;;;

어 그래! 죄송합니다. 읽지 않았습니다. 하지만 대답 해 주셔서 감사합니다!
