### ISSUE TITLE
다음웹툰 결제한 유료회차를 받으려고하는데 쿠키는 어디에서 넣나요?

### ISSUE THREAD

**Issue by ghost** [Seo-Rii/Webtoon_Downloader_UI#6]
CLI버전은 실행이되지않아 gui버전을 다운받았습니다
무료회차는 다운이 잘되는데 결제한 유료회차를 받기위해서는 쿠키값을 넣으라고하는데
어떻게 넣을수가있나요?

**Comment by seo-rii** [comment]
아직 GUI에서는 쿠키 관련 로직이 없습니다 :( CLI를 사용해 주시면 감사하겠습니다.

**Comment by seo-rii** [comment]
@samong2 그런데 CLI 실행이 안된다는것은 무슨 소리인가요? 오류메시지가 뜬다면 해당 내용을 복사해서 올려주신다면 감사하겠습니다.

**Comment by ghost** [comment]
![321](https://user-images.githubusercontent.com/77836090/115484953-b1625780-a28e-11eb-933a-d8bedd63c765.png)

빠른답변감사합니다
이런 문구들이 뜨고 바로 창이꺼져서 복사는못하고 스크린샷으로 올려드려요

**Comment by seo-rii** [comment]
저 옵션대로 실행시키면 됩니다. cmd를 열고 webtoon_downloader.exe -s * -f * --mergeAsPdf daum *** **** 와 같이 실행시키면 됩니다.

**Comment by ghost** [comment]
![KakaoTalk_20210421_130044918](https://user-images.githubusercontent.com/77836090/115495056-c8f70b80-a2a1-11eb-9a03-c6a1b2cc5973.png)
감사합니다
이런식으로 cmd건드는건 해본적이 없어서
차근차근 따라하다보니작업이되네요
무료회차는 말씀해주신거처럼하니 잘되는데 유료회차는 쿠키넣고하려니
스크린샷처럼 다운이 안되는데 해결방법이 있을까요?
webtoon_downloader.exe -s 22 -f 22 --mergeAsPng daum BurningEffect C:\webtoon cookie [*** *** *** *** ***]
이런식으로 썼고 다음은 쿠키가 HM_CU, HTS, PROF, TS, LSID 이렇게 필요해서 순서대로 써넣었습니다

**Comment by seo-rii** [comment]
파라미터에서 'cookie'는 빼고 넣으셔야 합니다

**Comment by ghost** [comment]
빠른 피드백 정말 감사합니다
아무것도 모르는 상태에서 이것저것 계속 물어서  귀찮게해드렸네요
말씀하신대로해서 정상적으로 완료했습니다
다시한번 감사드립니다
